library(largerscale)
library(rzmq)
HOST("127.0.0.1")
synchronizer <- init.socket(CONTEXT(), "ZMQ_REP")
bind.socket(synchronizer, paste0("tcp://", HOST(), ":0"))
write(deparse(bquote({
	library(largerscale)
	HOST("127.0.0.1")
	debug(resume_parent)
	resume_parent(.(get.last.endpoint(synchronizer)))
	})), "test/child.R")
message <- receive.socket(synchronizer)
send.socket(synchronizer, "ACK")
