LOCATION <- location(address="localhost", port=1234L)

port <- function(x, ...) UseMethod("port")
address <- function(x, ...) UseMethod("address")
locate <- function(x, ...) UseMethod("locate")
identifier <- function(x, ...)
	if (missing(x)) identifier(6L) else UseMethod("identifier")
input <- function(x, ...) UseMethod("input")
value <- function(x, ...) UseMethod("value")
request <- function(x, ...) UseMethod("request")
store <- function(x, ...) UseMethod("store")
data <- function(x, ...) UseMethod("data")
output <- function(x, ...) UseMethod("output")
computation <- function(x, ...) UseMethod("computation")
do <- function(x, ...) UseMethod("do")
emerge <- function(x, ...) UseMethod("emerge")
send <- function(x, ...) UseMethod("send")
store <- function(x, ...) UseMethod("store")
key <- function(x, ...) UseMethod("key")
`value<-` <- function(x, value) UseMethod("value<-")
