LOCATION <- location(address="localhost", port=1234L)

port <- function(x, ...) UseMethod("port")
address <- function(x, ...) UseMethod("address")
locate <- function(x, ...) UseMethod("locate")
identifier <- function(x, ...) UseMethod("identifier")
input <- function(x, ...) UseMethod("input")
value <- function(x, ...) UseMethod("value")
request <- function(x, ...) UseMethod("request")
store <- function(x, ...) UseMethod("store")
data <- function(x, ...) UseMethod("data")
output <- function(x, ...) UseMethod("output")
computation <- function(x, ...) UseMethod("computation")
do <- function(x, ...) UseMethod("do")
emerge <- function(x, ...) UseMethod("emerge")
