LOCATION <- location(address="localhost", port=1234L)

port <- function(x, ...) UseMethod("port")
address <- function(x, ...) UseMethod("address")
locate <- function(x, ...) UseMethod("locate")
type <- function(x, ...) UseMethod("type")
key <- function(x, ...) UseMethod("key")
fun <- function(x, ...) UseMethod("fun")
identifier <- function(x, ...) UseMethod("identifier")
addl <- function(x, ...) UseMethod("addl")
input <- function(x, ...) UseMethod("input")
value <- function(x, ...) UseMethod("value")
request <- function(x, ...) UseMethod("request")
store <- function(x, ...) UseMethod("store")
data <- function(x, ...) UseMethod("data")
